services:
  api-favoritos:
    build: ./api-favoritos
    ports:
      - "5002:5002"
    environment:
      - POSTGRES_URL=postgres://user:password@postgres:5432/favoritos_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: favoritos_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: